const actionsTypes = {
  SET_ORDERS: 'SET_ORDERS',
  SET_CURRENT_CUSTOMER_ID: 'SET_CURRENT_CUSTOMER_ID',
  HANDLE_MODAL_VISIBILITY: 'HANDLE_MODAL_VISIBILITY',
  SET_ANCHOR: 'SET_ANCHOR',
  SET_IMAGE_ADDRESS: 'SET_IMAGE_ADDRESS',
  SET_SELECTED_ORDERS: 'SET_SELECTED_ORDERS',
  SET_SELECTED_ITEMS: 'SET_SELECTED_ITEMS',
};

export default actionsTypes;
